services:
  - type: web
    name: heroes-battle-server
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: "https://serwer399783.lh.pl,http://localhost:8080,http://127.0.0.1:8080"
      - key: DB_HOST
        value: sql177.lh.pl
      - key: DB_USER
        value: serwer399783
      - key: DB_PASSWORD
        value: Haslo098!
      - key: DB_NAME
        value: serwer399783_atEpic
      - key: DB_CONNECTION_LIMIT
        value: "10"
